FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache git

# Install air for hot reload (v1.61.5 supports Go 1.24)
RUN go install github.com/air-verse/air@v1.61.5

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8000

CMD ["air", "-c", ".air.toml"]
