/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo API - Public
 * Public API for Good Todo application
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTodoRequest,
  TodoListResponse,
  TodoResponse,
  UpdateTodoRequest
} from '.././model/components-schemas-todo';
import type {
  ErrorResponse
} from '.././model/components-schemas-error';
import type {
  GetPublicTodosParams,
  GetTodosParams
} from '.././model';

import { customInstance } from '../../axios-instance';




/**
 * @summary Get all todos for current user
 */
export const getTodos = (
    params?: GetTodosParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TodoListResponse>(
      {url: `/todos`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetTodosQueryKey = (params?: GetTodosParams,) => {
    return [
    `/todos`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTodosQueryOptions = <TData = Awaited<ReturnType<typeof getTodos>>, TError = ErrorResponse>(params?: GetTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodosQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodos>>> = ({ signal }) => getTodos(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTodosQueryResult = NonNullable<Awaited<ReturnType<typeof getTodos>>>
export type GetTodosQueryError = ErrorResponse


export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = ErrorResponse>(
 params: undefined |  GetTodosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodos>>,
          TError,
          Awaited<ReturnType<typeof getTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = ErrorResponse>(
 params?: GetTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodos>>,
          TError,
          Awaited<ReturnType<typeof getTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = ErrorResponse>(
 params?: GetTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all todos for current user
 */

export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = ErrorResponse>(
 params?: GetTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTodosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new todo
 */
export const createTodo = (
    createTodoRequest: CreateTodoRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TodoResponse>(
      {url: `/todos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTodoRequest, signal
    },
      );
    }
  


export const getCreateTodoMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext> => {

const mutationKey = ['createTodo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTodo>>, {data: CreateTodoRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTodo(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof createTodo>>>
    export type CreateTodoMutationBody = CreateTodoRequest
    export type CreateTodoMutationError = ErrorResponse

    /**
 * @summary Create a new todo
 */
export const useCreateTodo = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTodo>>,
        TError,
        {data: CreateTodoRequest},
        TContext
      > => {

      const mutationOptions = getCreateTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get public todos in the same tenant
 */
export const getPublicTodos = (
    params?: GetPublicTodosParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TodoListResponse>(
      {url: `/todos-public`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetPublicTodosQueryKey = (params?: GetPublicTodosParams,) => {
    return [
    `/todos-public`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPublicTodosQueryOptions = <TData = Awaited<ReturnType<typeof getPublicTodos>>, TError = ErrorResponse>(params?: GetPublicTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicTodos>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicTodosQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicTodos>>> = ({ signal }) => getPublicTodos(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicTodos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPublicTodosQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicTodos>>>
export type GetPublicTodosQueryError = ErrorResponse


export function useGetPublicTodos<TData = Awaited<ReturnType<typeof getPublicTodos>>, TError = ErrorResponse>(
 params: undefined |  GetPublicTodosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicTodos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicTodos>>,
          TError,
          Awaited<ReturnType<typeof getPublicTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicTodos<TData = Awaited<ReturnType<typeof getPublicTodos>>, TError = ErrorResponse>(
 params?: GetPublicTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicTodos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicTodos>>,
          TError,
          Awaited<ReturnType<typeof getPublicTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicTodos<TData = Awaited<ReturnType<typeof getPublicTodos>>, TError = ErrorResponse>(
 params?: GetPublicTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicTodos>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get public todos in the same tenant
 */

export function useGetPublicTodos<TData = Awaited<ReturnType<typeof getPublicTodos>>, TError = ErrorResponse>(
 params?: GetPublicTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicTodos>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPublicTodosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a todo by ID
 */
export const getTodo = (
    todoId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TodoResponse>(
      {url: `/todos/${todoId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTodoQueryKey = (todoId?: string,) => {
    return [
    `/todos/${todoId}`
    ] as const;
    }

    
export const getGetTodoQueryOptions = <TData = Awaited<ReturnType<typeof getTodo>>, TError = ErrorResponse>(todoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodoQueryKey(todoId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodo>>> = ({ signal }) => getTodo(todoId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(todoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTodoQueryResult = NonNullable<Awaited<ReturnType<typeof getTodo>>>
export type GetTodoQueryError = ErrorResponse


export function useGetTodo<TData = Awaited<ReturnType<typeof getTodo>>, TError = ErrorResponse>(
 todoId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodo>>,
          TError,
          Awaited<ReturnType<typeof getTodo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodo<TData = Awaited<ReturnType<typeof getTodo>>, TError = ErrorResponse>(
 todoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodo>>,
          TError,
          Awaited<ReturnType<typeof getTodo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodo<TData = Awaited<ReturnType<typeof getTodo>>, TError = ErrorResponse>(
 todoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a todo by ID
 */

export function useGetTodo<TData = Awaited<ReturnType<typeof getTodo>>, TError = ErrorResponse>(
 todoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTodoQueryOptions(todoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update a todo
 */
export const updateTodo = (
    todoId: string,
    updateTodoRequest: UpdateTodoRequest,
 ) => {
      
      
      return customInstance<TodoResponse>(
      {url: `/todos/${todoId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateTodoRequest
    },
      );
    }
  


export const getUpdateTodoMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{todoId: string;data: UpdateTodoRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{todoId: string;data: UpdateTodoRequest}, TContext> => {

const mutationKey = ['updateTodo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTodo>>, {todoId: string;data: UpdateTodoRequest}> = (props) => {
          const {todoId,data} = props ?? {};

          return  updateTodo(todoId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof updateTodo>>>
    export type UpdateTodoMutationBody = UpdateTodoRequest
    export type UpdateTodoMutationError = ErrorResponse

    /**
 * @summary Update a todo
 */
export const useUpdateTodo = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{todoId: string;data: UpdateTodoRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTodo>>,
        TError,
        {todoId: string;data: UpdateTodoRequest},
        TContext
      > => {

      const mutationOptions = getUpdateTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a todo
 */
export const deleteTodo = (
    todoId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/todos/${todoId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteTodoMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{todoId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{todoId: string}, TContext> => {

const mutationKey = ['deleteTodo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTodo>>, {todoId: string}> = (props) => {
          const {todoId} = props ?? {};

          return  deleteTodo(todoId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTodoMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodo>>>
    
    export type DeleteTodoMutationError = ErrorResponse

    /**
 * @summary Delete a todo
 */
export const useDeleteTodo = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{todoId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTodo>>,
        TError,
        {todoId: string},
        TContext
      > => {

      const mutationOptions = getDeleteTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    