/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo API - Public
 * Public API for Good Todo application
 * OpenAPI spec version: 0.0.1
 */

export type GetPublicTodosParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
