// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"good-todo-go/internal/ent/predicate"
	"good-todo-go/internal/ent/tenanttodoview"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantTodoViewUpdate is the builder for updating TenantTodoView entities.
type TenantTodoViewUpdate struct {
	config
	hooks    []Hook
	mutation *TenantTodoViewMutation
}

// Where appends a list predicates to the TenantTodoViewUpdate builder.
func (_u *TenantTodoViewUpdate) Where(ps ...predicate.TenantTodoView) *TenantTodoViewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantTodoViewUpdate) SetTenantID(v string) *TenantTodoViewUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableTenantID(v *string) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantTodoViewUpdate) SetUserID(v string) *TenantTodoViewUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableUserID(v *string) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *TenantTodoViewUpdate) SetUserName(v string) *TenantTodoViewUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableUserName(v *string) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *TenantTodoViewUpdate) SetUserEmail(v string) *TenantTodoViewUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableUserEmail(v *string) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TenantTodoViewUpdate) SetTitle(v string) *TenantTodoViewUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableTitle(v *string) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantTodoViewUpdate) SetDescription(v string) *TenantTodoViewUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableDescription(v *string) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCompleted sets the "completed" field.
func (_u *TenantTodoViewUpdate) SetCompleted(v bool) *TenantTodoViewUpdate {
	_u.mutation.SetCompleted(v)
	return _u
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableCompleted(v *bool) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetCompleted(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *TenantTodoViewUpdate) SetIsPublic(v bool) *TenantTodoViewUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableIsPublic(v *bool) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TenantTodoViewUpdate) SetDueDate(v time.Time) *TenantTodoViewUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableDueDate(v *time.Time) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TenantTodoViewUpdate) ClearDueDate() *TenantTodoViewUpdate {
	_u.mutation.ClearDueDate()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TenantTodoViewUpdate) SetCompletedAt(v time.Time) *TenantTodoViewUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableCompletedAt(v *time.Time) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TenantTodoViewUpdate) ClearCompletedAt() *TenantTodoViewUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TenantTodoViewUpdate) SetCreatedAt(v time.Time) *TenantTodoViewUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableCreatedAt(v *time.Time) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantTodoViewUpdate) SetUpdatedAt(v time.Time) *TenantTodoViewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TenantTodoViewUpdate) SetNillableUpdatedAt(v *time.Time) *TenantTodoViewUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the TenantTodoViewMutation object of the builder.
func (_u *TenantTodoViewUpdate) Mutation() *TenantTodoViewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantTodoViewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantTodoViewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantTodoViewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantTodoViewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TenantTodoViewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenanttodoview.Table, tenanttodoview.Columns, sqlgraph.NewFieldSpec(tenanttodoview.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(tenanttodoview.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(tenanttodoview.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(tenanttodoview.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(tenanttodoview.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(tenanttodoview.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenanttodoview.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Completed(); ok {
		_spec.SetField(tenanttodoview.FieldCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(tenanttodoview.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(tenanttodoview.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(tenanttodoview.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(tenanttodoview.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(tenanttodoview.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tenanttodoview.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenanttodoview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenanttodoview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantTodoViewUpdateOne is the builder for updating a single TenantTodoView entity.
type TenantTodoViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantTodoViewMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantTodoViewUpdateOne) SetTenantID(v string) *TenantTodoViewUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableTenantID(v *string) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantTodoViewUpdateOne) SetUserID(v string) *TenantTodoViewUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableUserID(v *string) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *TenantTodoViewUpdateOne) SetUserName(v string) *TenantTodoViewUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableUserName(v *string) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *TenantTodoViewUpdateOne) SetUserEmail(v string) *TenantTodoViewUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableUserEmail(v *string) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TenantTodoViewUpdateOne) SetTitle(v string) *TenantTodoViewUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableTitle(v *string) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantTodoViewUpdateOne) SetDescription(v string) *TenantTodoViewUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableDescription(v *string) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCompleted sets the "completed" field.
func (_u *TenantTodoViewUpdateOne) SetCompleted(v bool) *TenantTodoViewUpdateOne {
	_u.mutation.SetCompleted(v)
	return _u
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableCompleted(v *bool) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetCompleted(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *TenantTodoViewUpdateOne) SetIsPublic(v bool) *TenantTodoViewUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableIsPublic(v *bool) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TenantTodoViewUpdateOne) SetDueDate(v time.Time) *TenantTodoViewUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableDueDate(v *time.Time) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TenantTodoViewUpdateOne) ClearDueDate() *TenantTodoViewUpdateOne {
	_u.mutation.ClearDueDate()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TenantTodoViewUpdateOne) SetCompletedAt(v time.Time) *TenantTodoViewUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableCompletedAt(v *time.Time) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TenantTodoViewUpdateOne) ClearCompletedAt() *TenantTodoViewUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TenantTodoViewUpdateOne) SetCreatedAt(v time.Time) *TenantTodoViewUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableCreatedAt(v *time.Time) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantTodoViewUpdateOne) SetUpdatedAt(v time.Time) *TenantTodoViewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TenantTodoViewUpdateOne) SetNillableUpdatedAt(v *time.Time) *TenantTodoViewUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the TenantTodoViewMutation object of the builder.
func (_u *TenantTodoViewUpdateOne) Mutation() *TenantTodoViewMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantTodoViewUpdate builder.
func (_u *TenantTodoViewUpdateOne) Where(ps ...predicate.TenantTodoView) *TenantTodoViewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantTodoViewUpdateOne) Select(field string, fields ...string) *TenantTodoViewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantTodoView entity.
func (_u *TenantTodoViewUpdateOne) Save(ctx context.Context) (*TenantTodoView, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantTodoViewUpdateOne) SaveX(ctx context.Context) *TenantTodoView {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantTodoViewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantTodoViewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TenantTodoViewUpdateOne) sqlSave(ctx context.Context) (_node *TenantTodoView, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenanttodoview.Table, tenanttodoview.Columns, sqlgraph.NewFieldSpec(tenanttodoview.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantTodoView.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenanttodoview.FieldID)
		for _, f := range fields {
			if !tenanttodoview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenanttodoview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(tenanttodoview.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(tenanttodoview.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(tenanttodoview.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(tenanttodoview.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(tenanttodoview.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenanttodoview.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Completed(); ok {
		_spec.SetField(tenanttodoview.FieldCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(tenanttodoview.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(tenanttodoview.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(tenanttodoview.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(tenanttodoview.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(tenanttodoview.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tenanttodoview.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenanttodoview.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TenantTodoView{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenanttodoview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
