// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"good-todo-go/internal/ent/tenanttodoview"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantTodoViewCreate is the builder for creating a TenantTodoView entity.
type TenantTodoViewCreate struct {
	config
	mutation *TenantTodoViewMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *TenantTodoViewCreate) SetTenantID(v string) *TenantTodoViewCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TenantTodoViewCreate) SetUserID(v string) *TenantTodoViewCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUserName sets the "user_name" field.
func (_c *TenantTodoViewCreate) SetUserName(v string) *TenantTodoViewCreate {
	_c.mutation.SetUserName(v)
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *TenantTodoViewCreate) SetUserEmail(v string) *TenantTodoViewCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *TenantTodoViewCreate) SetTitle(v string) *TenantTodoViewCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TenantTodoViewCreate) SetDescription(v string) *TenantTodoViewCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetCompleted sets the "completed" field.
func (_c *TenantTodoViewCreate) SetCompleted(v bool) *TenantTodoViewCreate {
	_c.mutation.SetCompleted(v)
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *TenantTodoViewCreate) SetDueDate(v time.Time) *TenantTodoViewCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_c *TenantTodoViewCreate) SetNillableDueDate(v *time.Time) *TenantTodoViewCreate {
	if v != nil {
		_c.SetDueDate(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *TenantTodoViewCreate) SetCompletedAt(v time.Time) *TenantTodoViewCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *TenantTodoViewCreate) SetNillableCompletedAt(v *time.Time) *TenantTodoViewCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantTodoViewCreate) SetCreatedAt(v time.Time) *TenantTodoViewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantTodoViewCreate) SetNillableCreatedAt(v *time.Time) *TenantTodoViewCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantTodoViewCreate) SetUpdatedAt(v time.Time) *TenantTodoViewCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantTodoViewCreate) SetNillableUpdatedAt(v *time.Time) *TenantTodoViewCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TenantTodoViewCreate) SetID(v string) *TenantTodoViewCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TenantTodoViewMutation object of the builder.
func (_c *TenantTodoViewCreate) Mutation() *TenantTodoViewMutation {
	return _c.mutation
}

// Save creates the TenantTodoView in the database.
func (_c *TenantTodoViewCreate) Save(ctx context.Context) (*TenantTodoView, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantTodoViewCreate) SaveX(ctx context.Context) *TenantTodoView {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantTodoViewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantTodoViewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantTodoViewCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenanttodoview.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tenanttodoview.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantTodoViewCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenantTodoView.tenant_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TenantTodoView.user_id"`)}
	}
	if _, ok := _c.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`ent: missing required field "TenantTodoView.user_name"`)}
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		return &ValidationError{Name: "user_email", err: errors.New(`ent: missing required field "TenantTodoView.user_email"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "TenantTodoView.title"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "TenantTodoView.description"`)}
	}
	if _, ok := _c.mutation.Completed(); !ok {
		return &ValidationError{Name: "completed", err: errors.New(`ent: missing required field "TenantTodoView.completed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantTodoView.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TenantTodoView.updated_at"`)}
	}
	return nil
}

func (_c *TenantTodoViewCreate) sqlSave(ctx context.Context) (*TenantTodoView, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TenantTodoView.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantTodoViewCreate) createSpec() (*TenantTodoView, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantTodoView{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenanttodoview.Table, sqlgraph.NewFieldSpec(tenanttodoview.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tenanttodoview.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(tenanttodoview.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.UserName(); ok {
		_spec.SetField(tenanttodoview.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(tenanttodoview.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(tenanttodoview.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(tenanttodoview.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Completed(); ok {
		_spec.SetField(tenanttodoview.FieldCompleted, field.TypeBool, value)
		_node.Completed = value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(tenanttodoview.FieldDueDate, field.TypeTime, value)
		_node.DueDate = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(tenanttodoview.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenanttodoview.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenanttodoview.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TenantTodoViewCreateBulk is the builder for creating many TenantTodoView entities in bulk.
type TenantTodoViewCreateBulk struct {
	config
	err      error
	builders []*TenantTodoViewCreate
}

// Save creates the TenantTodoView entities in the database.
func (_c *TenantTodoViewCreateBulk) Save(ctx context.Context) ([]*TenantTodoView, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantTodoView, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantTodoViewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantTodoViewCreateBulk) SaveX(ctx context.Context) []*TenantTodoView {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantTodoViewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantTodoViewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
