// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"good-todo-go/internal/ent/predicate"
	"good-todo-go/internal/ent/tenanttodoview"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantTodoViewDelete is the builder for deleting a TenantTodoView entity.
type TenantTodoViewDelete struct {
	config
	hooks    []Hook
	mutation *TenantTodoViewMutation
}

// Where appends a list predicates to the TenantTodoViewDelete builder.
func (_d *TenantTodoViewDelete) Where(ps ...predicate.TenantTodoView) *TenantTodoViewDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TenantTodoViewDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantTodoViewDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TenantTodoViewDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenanttodoview.Table, sqlgraph.NewFieldSpec(tenanttodoview.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TenantTodoViewDeleteOne is the builder for deleting a single TenantTodoView entity.
type TenantTodoViewDeleteOne struct {
	_d *TenantTodoViewDelete
}

// Where appends a list predicates to the TenantTodoViewDelete builder.
func (_d *TenantTodoViewDeleteOne) Where(ps ...predicate.TenantTodoView) *TenantTodoViewDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TenantTodoViewDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenanttodoview.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantTodoViewDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
