/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo API - Public
 * Public API for Good Todo application
 * OpenAPI spec version: 0.0.1
 */
import type { UserResponse } from '../components-schemas-user/userResponse';

export interface AuthResponse {
  access_token?: string;
  refresh_token?: string;
  token_type?: string;
  /** Access token expiration time in seconds */
  expires_in?: number;
  user?: UserResponse;
}
