/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo API - Public
 * Public API for Good Todo application
 * OpenAPI spec version: 0.0.1
 */

export interface RegisterRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  name?: string;
  /** Tenant identifier (slug) */
  tenant_slug: string;
}
