/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo API - Public
 * Public API for Good Todo application
 * OpenAPI spec version: 0.0.1
 */
import type { ErrorResponseDetails } from './errorResponseDetails';

export interface ErrorResponse {
  code?: string;
  message?: string;
  details?: ErrorResponseDetails;
}
