/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo API - Public
 * Public API for Good Todo application
 * OpenAPI spec version: 0.0.1
 */

export interface CreateTodoRequest {
  /** @minLength 1 */
  title: string;
  description?: string;
  /** If true, visible to all users in the same tenant */
  is_public?: boolean;
  due_date?: string;
}
