/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo API - Public
 * Public API for Good Todo application
 * OpenAPI spec version: 0.0.1
 */

export type UserResponseRole = typeof UserResponseRole[keyof typeof UserResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRole = {
  admin: 'admin',
  member: 'member',
} as const;
