/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo API - Public
 * Public API for Good Todo application
 * OpenAPI spec version: 0.0.1
 */
import type { UserResponseRole } from './userResponseRole';

export interface UserResponse {
  id?: string;
  email?: string;
  name?: string;
  role?: UserResponseRole;
  email_verified?: boolean;
  tenant_id?: string;
  created_at?: string;
  updated_at?: string;
}
