// Code generated by MockGen. DO NOT EDIT.
// Source: uuid.go
//
// Generated by this command:
//
//	mockgen -source=uuid.go -destination=mock/uuid.go -package=mock_pkg
//

// Package mock_pkg is a generated GoMock package.
package mock_pkg

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIUUIDGenerator is a mock of IUUIDGenerator interface.
type MockIUUIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIUUIDGeneratorMockRecorder
	isgomock struct{}
}

// MockIUUIDGeneratorMockRecorder is the mock recorder for MockIUUIDGenerator.
type MockIUUIDGeneratorMockRecorder struct {
	mock *MockIUUIDGenerator
}

// NewMockIUUIDGenerator creates a new mock instance.
func NewMockIUUIDGenerator(ctrl *gomock.Controller) *MockIUUIDGenerator {
	mock := &MockIUUIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIUUIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUUIDGenerator) EXPECT() *MockIUUIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockIUUIDGenerator) Generate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockIUUIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockIUUIDGenerator)(nil).Generate))
}
